spring:
  main:
    allow-bean-definition-overriding: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/${MYSQL_DATABASE:demo_test}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  hikari:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    change-log: classpath:/liquibase/test.xml
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
